let wwg="https://html.spec.whatwg.org/multipage";
let mdn="https://developer.mozilla.org/en-US/docs/Web";
let el="HTML element";
let att="HTML attribute";
let a="ARIA attribute";

let noMdnEntry = '‼️ No page exists for this at MDN';

window.htmlData = [
    /* ELEMENTS*/
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-a-element","mdnUrl": mdn + "/HTML/Reference/Elements/a","title": "`a` (Anchor)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-abbr-element","mdnUrl": mdn + "/HTML/Reference/Elements/abbr","title": "`abbr` (Abbreviation)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-address-element","mdnUrl": mdn + "/HTML/Reference/Elements/address","title": "`address` (Contact Address)","category": el},
        {"whatwgUrl": wwg + "/image-maps.html#the-area-element","mdnUrl": mdn + "/HTML/Reference/Elements/area","title": "`area` (Image Map Area)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-article-element","mdnUrl": mdn + "/HTML/Reference/Elements/article","title": "`article` (Article Contents)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-aside-element","mdnUrl": mdn + "/HTML/Reference/Elements/aside","title": "`aside` (Aside)","category": el},
        {"whatwgUrl": wwg + "/media.html#the-audio-element","mdnUrl": mdn + "/HTML/Reference/Elements/audio","title": "`audio` (Embed Audio)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-b-element","mdnUrl": mdn + "/HTML/Reference/Elements/b","title": "`b` (Bring Attention To)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-base-element","mdnUrl": mdn + "/HTML/Reference/Elements/base","title": "`base` (Document Base URL)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-bdi-element","mdnUrl": mdn + "/HTML/Reference/Elements/bdi","title": "`bdi` (Bidirectional Isolate)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-bdo-element","mdnUrl": mdn + "/HTML/Reference/Elements/bdo","title": "`bdo` (Bidirectional Text Override)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-blockquote-element","mdnUrl": mdn + "/HTML/Reference/Elements/blockquote","title": "`blockquote` (Block Quotation)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-body-element","mdnUrl": mdn + "/HTML/Reference/Elements/body","title": "`body` (Document Body)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-br-element","mdnUrl": mdn + "/HTML/Reference/Elements/br","title": "`br` (Line Break)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-button-element","mdnUrl": mdn + "/HTML/Reference/Elements/button","title": "`button` (Button)","category": el},
        {"whatwgUrl": wwg + "/canvas.html#the-canvas-element","mdnUrl": mdn + "/HTML/Reference/Elements/canvas","title": "`canvas` (Graphics Canvas)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-caption-element","mdnUrl": mdn + "/HTML/Reference/Elements/caption","title": "`caption` (Table Caption)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-cite-element","mdnUrl": mdn + "/HTML/Reference/Elements/cite","title": "`cite` (Citation)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-code-element","mdnUrl": mdn + "/HTML/Reference/Elements/code","title": "`code` (Inline Code)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-col-element","mdnUrl": mdn + "/HTML/Reference/Elements/col","title": "`col` (Table Column)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-colgroup-element","mdnUrl": mdn + "/HTML/Reference/Elements/colgroup","title": "`colgroup` (Table Column Group)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-data-element","mdnUrl": mdn + "/HTML/Reference/Elements/data","title": "`data` (Data)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-datalist-element","mdnUrl": mdn + "/HTML/Reference/Elements/datalist","title": "`datalist` (HTML Data List)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-dd-element","mdnUrl": mdn + "/HTML/Reference/Elements/dd","title": "`dd` (Description Details)","category": el},
        {"whatwgUrl": wwg + "/edits.html#the-del-element","mdnUrl": mdn + "/HTML/Reference/Elements/del","title": "`del` (Deleted Text)","category": el},
        {"whatwgUrl": wwg + "/interactive-elements.html#the-details-element","mdnUrl": mdn + "/HTML/Reference/Elements/details","title": "`details` (Details disclosure)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-dfn-element","mdnUrl": mdn + "/HTML/Reference/Elements/dfn","title": "`dfn` (Definition)","category": el},
        {"whatwgUrl": wwg + "/interactive-elements.html#the-dialog-element","mdnUrl": mdn + "/HTML/Reference/Elements/dialog","title": "`dialog` (Dialog)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-div-element","mdnUrl": mdn + "/HTML/Reference/Elements/div","title": "`div` (Content Division)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-dl-element","mdnUrl": mdn + "/HTML/Reference/Elements/dl","title": "`dl` (Description List)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-dt-element","mdnUrl": mdn + "/HTML/Reference/Elements/dt","title": "`dt` (Description Term)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-em-element","mdnUrl": mdn + "/HTML/Reference/Elements/em","title": "`em` (Emphasis)","category": el},
        {"whatwgUrl": wwg + "/iframe-embed-object.html#the-embed-element","mdnUrl": mdn + "/HTML/Reference/Elements/embed","title": "`embed` (Embed External Content)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-fieldset-element","mdnUrl": mdn + "/HTML/Reference/Elements/fieldset","title": "`fieldset` (Field Set)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-figcaption-element","mdnUrl": mdn + "/HTML/Reference/Elements/figcaption","title": "`figcaption` (Figure Caption)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-figure-element","mdnUrl": mdn + "/HTML/Reference/Elements/figure","title": "`figure` (Figure with Optional Caption)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-footer-element","mdnUrl": mdn + "/HTML/Reference/Elements/footer","title": "`footer` (Footer)","category": el},
        {"whatwgUrl": wwg + "/forms.html#the-form-element","mdnUrl": mdn + "/HTML/Reference/Elements/form","title": "`form` (Form)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-head-element","mdnUrl": mdn + "/HTML/Reference/Elements/head","title": "`head` (Document Metadata (Header))","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-header-element","mdnUrl": mdn + "/HTML/Reference/Elements/header","title": "`header` (Header)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-hgroup-element","mdnUrl": mdn + "/HTML/Reference/Elements/hgroup","title": "`hgroup` (Heading Group)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-hr-element","mdnUrl": mdn + "/HTML/Reference/Elements/hr","title": "`hr` (Thematic Break (Horizontal Rule))","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-html-element","mdnUrl": mdn + "/HTML/Reference/Elements/html","title": "`html` (HTML Document / Root)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-i-element","mdnUrl": mdn + "/HTML/Reference/Elements/i","title": "`i` (Idiomatic Text)","category": el},
        {"whatwgUrl": wwg + "/iframe-embed-object.html#the-iframe-element","mdnUrl": mdn + "/HTML/Reference/Elements/iframe","title": "`iframe` (Inline Frame)","category": el},
        {"whatwgUrl": wwg + "/embedded-content.html#the-img-element","mdnUrl": mdn + "/HTML/Reference/Elements/img","title": "`img` (Image Embed)","category": el},
        {"whatwgUrl": wwg + "/input.html#the-input-element","mdnUrl": mdn + "/HTML/Reference/Elements/input","title": "`input` (HTML Input)","category": el},
        {"whatwgUrl": wwg + "/edits.html#the-ins-element","mdnUrl": mdn + "/HTML/Reference/Elements/ins","title": "`ins` (Inserted Text)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-kbd-element","mdnUrl": mdn + "/HTML/Reference/Elements/kbd","title": "`kbd` (Keyboard Input)","category": el},
        {"whatwgUrl": wwg + "/forms.html#the-label-element","mdnUrl": mdn + "/HTML/Reference/Elements/label","title": "`label` (Label)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-legend-element","mdnUrl": mdn + "/HTML/Reference/Elements/legend","title": "`legend` (Field Set Legend)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-li-element","mdnUrl": mdn + "/HTML/Reference/Elements/li","title": "`li` (List Item)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-link-element","mdnUrl": mdn + "/HTML/Reference/Elements/link","title": "`link` (External Resource Link)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-main-element","mdnUrl": mdn + "/HTML/Reference/Elements/main","title": "`main` (Main)","category": el},
        {"whatwgUrl": wwg + "/image-maps.html#the-map-element","mdnUrl": mdn + "/HTML/Reference/Elements/map","title": "`map` (Image Map)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-mark-element","mdnUrl": mdn + "/HTML/Reference/Elements/mark","title": "`mark` (Mark Text)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-menu-element","mdnUrl": mdn + "/HTML/Reference/Elements/menu","title": "`menu` (Menu)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-meta-element","mdnUrl": mdn + "/HTML/Reference/Elements/meta","title": "`meta` (metadata)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-meter-element","mdnUrl": mdn + "/HTML/Reference/Elements/meter","title": "`meter` (HTML Meter)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-nav-element","mdnUrl": mdn + "/HTML/Reference/Elements/nav","title": "`nav` (Navigation Section)","category": el},
        {"whatwgUrl": wwg + "/scripting.html#the-noscript-element","mdnUrl": mdn + "/HTML/Reference/Elements/noscript","title": "`noscript` (Noscript)","category": el},
        {"whatwgUrl": wwg + "/iframe-embed-object.html#the-object-element","mdnUrl": mdn + "/HTML/Reference/Elements/object","title": "`object` (External Object)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-ol-element","mdnUrl": mdn + "/HTML/Reference/Elements/ol","title": "`ol` (Ordered List)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-optgroup-element","mdnUrl": mdn + "/HTML/Reference/Elements/optgroup","title": "`optgroup` (Option Group)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-option-element","mdnUrl": mdn + "/HTML/Reference/Elements/option","title": "`option` (HTML Option)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-output-element","mdnUrl": mdn + "/HTML/Reference/Elements/output","title": "`output` (Output)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-p-element","mdnUrl": mdn + "/HTML/Reference/Elements/p","title": "`p` (Paragraph)","category": el},
        {"whatwgUrl": wwg + "/iframe-embed-object.html#the-param-element","mdnUrl": mdn + "/HTML/Reference/Elements/param","title": "`param` (Object Parameter)","category": el},
        {"whatwgUrl": wwg + "/embedded-content.html#the-picture-element","mdnUrl": mdn + "/HTML/Reference/Elements/picture","title": "`picture` (Picture)","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-pre-element","mdnUrl": mdn + "/HTML/Reference/Elements/pre","title": "`pre` (Preformatted Text)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-progress-element","mdnUrl": mdn + "/HTML/Reference/Elements/progress","title": "`progress` (Progress Indicator)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-q-element","mdnUrl": mdn + "/HTML/Reference/Elements/q","title": "`q` (Inline Quotation)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-rp-element","mdnUrl": mdn + "/HTML/Reference/Elements/rp","title": "`rp` (Ruby Fallback Parenthesis)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-rt-element","mdnUrl": mdn + "/HTML/Reference/Elements/rt","title": "`rt` (Ruby Text)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-ruby-element","mdnUrl": mdn + "/HTML/Reference/Elements/ruby","title": "`ruby` (Ruby Annotation)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-s-element","mdnUrl": mdn + "/HTML/Reference/Elements/s","title": "`s` (Strikethrough)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-samp-element","mdnUrl": mdn + "/HTML/Reference/Elements/samp","title": "`samp` (Sample Output)","category": el},
        {"whatwgUrl": wwg + "/scripting.html#the-script-element","mdnUrl": mdn + "/HTML/Reference/Elements/script","title": "`script` (Script)","category": el},
        {"whatwgUrl": wwg + "/sections.html#the-section-element","mdnUrl": mdn + "/HTML/Reference/Elements/section","title": "`section` (Generic Section)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-select-element","mdnUrl": mdn + "/HTML/Reference/Elements/select","title": "`select` (HTML Select)","category": el},
        {"whatwgUrl": wwg + "/scripting.html#the-slot-element","mdnUrl": mdn + "/HTML/Reference/Elements/slot","title": "`slot` (Web Component Slot)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-small-element","mdnUrl": mdn + "/HTML/Reference/Elements/small","title": "`small` (Side Comment)","category": el},
        {"whatwgUrl": wwg + "/embedded-content.html#the-source-element","mdnUrl": mdn + "/HTML/Reference/Elements/source","title": "`source` (Media or Image Source)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-span-element","mdnUrl": mdn + "/HTML/Reference/Elements/span","title": "`span` (Content Span)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-strong-element","mdnUrl": mdn + "/HTML/Reference/Elements/strong","title": "`strong` (Strong Importance)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-style-element","mdnUrl": mdn + "/HTML/Reference/Elements/style","title": "`style` (Style Information)","category": el},
        {"whatwgUrl": wwg + "/interactive-elements.html#the-summary-element","mdnUrl": mdn + "/HTML/Reference/Elements/summary","title": "`summary` (Disclosure Summary)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-table-element","mdnUrl": mdn + "/HTML/Reference/Elements/table","title": "`table` (Table)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-tbody-element","mdnUrl": mdn + "/HTML/Reference/Elements/tbody","title": "`tbody` (Table Body)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-td-element","mdnUrl": mdn + "/HTML/Reference/Elements/td","title": "`td` (Table Data Cell)","category": el},
        {"whatwgUrl": wwg + "/scripting.html#the-template-element","mdnUrl": mdn + "/HTML/Reference/Elements/template","title": "`template` (Content Template)","category": el},
        {"whatwgUrl": wwg + "/form-elements.html#the-textarea-element","mdnUrl": mdn + "/HTML/Reference/Elements/textarea","title": "`textarea` (Textarea)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-tfoot-element","mdnUrl": mdn + "/HTML/Reference/Elements/tfoot","title": "`tfoot` (Table Foot)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-th-element","mdnUrl": mdn + "/HTML/Reference/Elements/th","title": "`th` (Table Header)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-thead-element","mdnUrl": mdn + "/HTML/Reference/Elements/thead","title": "`thead` (Table Head)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-time-element","mdnUrl": mdn + "/HTML/Reference/Elements/time","title": "`time` ((Date) Time)","category": el},
        {"whatwgUrl": wwg + "/semantics.html#the-title-element","mdnUrl": mdn + "/HTML/Reference/Elements/title","title": "`title` (Document Title)","category": el},
        {"whatwgUrl": wwg + "/tables.html#the-tr-element","mdnUrl": mdn + "/HTML/Reference/Elements/tr","title": "`tr` (Table Row)","category": el},
        {"whatwgUrl": wwg + "/media.html#the-track-element","mdnUrl": mdn + "/HTML/Reference/Elements/track","title": "`track` (Embed Text Track)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-u-element","mdnUrl": mdn + "/HTML/Reference/Elements/u","title": "`u` (Unarticulated Annotation (Underline))","category": el},
        {"whatwgUrl": wwg + "/grouping-content.html#the-ul-element","mdnUrl": mdn + "/HTML/Reference/Elements/ul","title": "`ul` (Unordered List)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-var-element","mdnUrl": mdn + "/HTML/Reference/Elements/var","title": "`var` (Variable)","category": el},
        {"whatwgUrl": wwg + "/media.html#the-video-element","mdnUrl": mdn + "/HTML/Reference/Elements/video","title": "`video` (Video Embed)","category": el},
        {"whatwgUrl": wwg + "/text-level-semantics.html#the-wbr-element","mdnUrl": mdn + "/HTML/Reference/Elements/wb","title": "`wbr` (Line Break Opportunity)","category": el},
    /* ATTRIBUTES */
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/accept","title": "`accept`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#accept-charset","title": "`accept-charset`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/accesskey","title": "`accesskey`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#allow","title": "`action`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#actionallow","title": "`actionallow`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/link#as","title": "`as`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/script#async","title": "`async`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/autocapitalize","title": "`autocapitalize`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/autocomplete","title": "`autocomplete`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/capture","title": "`capture`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/meta#charset","title": "`charset`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/input#checked","title": "`checked`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/class","title": "`class`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/textarea#cols","title": "`cols`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/content","title": "`content`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/contenteditable","title": "`contenteditable`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/area#coords","title": "`coords`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/crossorigin","title": "`crossorigin`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/API/HTMLIFrameElement/csp","title": "`csp`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/object#data","title": "`data`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/data-*","title": "`data-*`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/img#decoding","title": "`decoding`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/track#default","title": "`default`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/script#defer","title": "`defer`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/dir","title": "`dir`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/dirname","title": "`dirname`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/disabled","title": "`disabled`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/draggable","title": "`draggable`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#enctype","title": "`enctype`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/enterkeyhint","title": "`enterkeyhint`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/elementtiming","title": "`elementtiming`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/for","title": "`for`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/hidden","title": "`hidden`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/meter#high","title": "`high`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/meta/http-equiv","title": "`http-equiv`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/id","title": "`id`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Security/Subresource_Integrity","title": "`integrity`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/img#ismap","title": "`ismap`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/itemprop","title": "`itemprop`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/track#kind","title": "`kind`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/lang","title": "`lang`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/script#language","title": "`language`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/input#list","title": "`list`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/meter#low","title": "`low`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/max","title": "`max`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/maxlength","title": "`maxlength`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/minlength","title": "`minlength`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#method","title": "`method`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/min","title": "`min`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/multiple","title": "`multiple`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/form#novalidate","title": "`novalidate`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/meter#optimum","title": "`optimum`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/pattern","title": "`pattern`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/a#ping","title": "`ping`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/placeholder","title": "`placeholder`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/video#playsinline","title": "`playsinline`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/video#poster","title": "`poster`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/readonly","title": "`readonly`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/rel","title": "`rel`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/required","title": "`required`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/ol#reversed","title": "`reversed`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Roles","title": "`role`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/textarea#rows","title": "`rows`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/iframe#sandbox","title": "`sandbox`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/th#scope","title": "`scope`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/option#selected","title": "`selected`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/size","title": "`size`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/slot","title": "`slot`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/spellcheck","title": "`spellcheck`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/iframe#srcdoc","title": "`srcdoc`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/track#srclang","title": "`srclang`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/ol#start","title": "`start`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Attributes/step","title": "`step`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/style","title": "`style`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/table#summary","title": "`summary`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/tabindex","title": "`tabindex`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/title","title": "`title`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Global_attributes/translate","title": "`translate`","category": att},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/HTML/Reference/Elements/textarea#wrap","title": "`wrap`","category": att},
    /* ARIA */
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-activedescendant","title": "`aria-activedescendant`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-atomic","title": "`aria-atomic`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-autocomplete","title": "`aria-autocomplete`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-busy","title": "`aria-busy`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-checked","title": "`aria-checked`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-colcount","title": "`aria-colcount`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-colindex","title": "`aria-colindex`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-colspan","title": "`aria-colspan`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-controls","title": "`aria-controls`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-current","title": "`aria-current`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-describedby","title": "`aria-describedby`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-description","title": "`aria-description`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-details","title": "`aria-details`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-disabled","title": "`aria-disabled`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-dropeffect","title": "`aria-dropeffect`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-errormessage","title": "`aria-errormessage`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-expanded","title": "`aria-expanded`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-flowto","title": "`aria-flowto`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-grabbed","title": "`aria-grabbed`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-haspopup","title": "`aria-haspopup`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-hidden","title": "`aria-hidden`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-invalid","title": "`aria-invalid`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-keyshortcuts","title": "`aria-keyshortcuts`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-label","title": "`aria-label`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-labelledby","title": "`aria-labelledby`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-level","title": "`aria-level`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-live","title": "`aria-live`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-modal","title": "`aria-modal`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-multiline","title": "`aria-multiline`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-multiselectable","title": "`aria-multiselectable`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-orientation","title": "`aria-orientation`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-owns","title": "`aria-owns`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-placeholder","title": "`aria-placeholder`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-posinset","title": "`aria-posinset`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-pressed","title": "`aria-pressed`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-readonly","title": "`aria-readonly`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-relevant","title": "`aria-relevant`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-required","title": "`aria-required`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-roledescription","title": "`aria-roledescription`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-rowcount","title": "`aria-rowcount`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-rowindex","title": "`aria-rowindex`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-rowspan","title": "`aria-rowspan`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-selected","title": "`aria-selected`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-setsize","title": "`aria-setsize`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-sort","title": "`aria-sort`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-valuemax","title": "`aria-valuemax`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-valuemin","title": "`aria-valuemin`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-valuenow","title": "`aria-valuenow`","category": a},
        {"whatwgUrl": "N/A","mdnUrl": mdn + "/Accessibility/ARIA/Reference/Attributes/aria-valuetext","title": "`aria-valuetext`","category": a},
    /* ATTRIBUTES WITH NO ENTRY */
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`alt`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`autoplay`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`background`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`bgcolor`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`border`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`cite`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`color`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`colspan`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`controls`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`datetime`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`download`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`form`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`formaction`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`formenctype`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`formmethod`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`formnovalidate`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`formtarget`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`headers`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`height`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`href`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`hreflang`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`inputmode`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`label`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`loading`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`loop`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`media`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`muted`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`name`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`open`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`preload`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`referrerpolicy`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`rowspan`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`shape`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`sizes`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`span`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`src`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`srcset`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`target`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`type`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`usemap`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`value`" + noMdnEntry,"category": att},
        {"whatwgUrl": "N/A","mdnUrl": "N/A","title": "`width`" + noMdnEntry,"category": att},
]
